<UserControl x:Class="Urbbox.SlabAssembler.Views.AlgorythimControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:System="clr-namespace:System;assembly=mscorlib"
             xmlns:local="clr-namespace:Urbbox.SlabAssembler"
             xmlns:vm="clr-namespace:Urbbox.SlabAssembler.ViewModels"
             xmlns:ac="clr-namespace:Autodesk.AutoCAD.Customization;assembly=AcCui"
             xmlns:cv="clr-namespace:Urbbox.SlabAssembler.ViewModels.Converters"
             mc:Ignorable="d"
             d:DataContext="{d:DesignInstance vm:AlgorythimViewModel}"
             d:DesignHeight="600" d:DesignWidth="300" Background="White">

    <UserControl.Resources>
        <ObjectDataProvider x:Key="OrientationsList" MethodName="GetValues" ObjectType="{x:Type System:Enum}">
            <ObjectDataProvider.MethodParameters>
                <x:Type TypeName="ac:Orientation" />
            </ObjectDataProvider.MethodParameters>
        </ObjectDataProvider>
    </UserControl.Resources>

    <StackPanel CanHorizontallyScroll="True" MinWidth="300">
        <GroupBox Header="零件图选项"  Margin="10">
            <StackPanel Margin="5">
                <CheckBox Content="使用LDS" IsChecked="{Binding Options.UseLds, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Margin="0,5,0,0" />
                <CheckBox Content="使用LP Final" IsChecked="{Binding Options.UseEndLp, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Margin="0,5,0,0" />
                <Label Content="启动LP" Margin="0,5,0,0" />
                <ComboBox ItemsSource="{Binding Path=StartLpList}" SelectedItem="{Binding SelectedStartLp, Mode=TwoWay}"  DisplayMemberPath="Name" />
            </StackPanel>
        </GroupBox>

        <GroupBox Header="距离常数" Margin="10">
            <StackPanel Margin="10">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="50*" />
                        <ColumnDefinition Width="35*" />
                        <ColumnDefinition Width="15*" />
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="35" />
                        <RowDefinition Height="35" />
                        <RowDefinition Height="35" />
                    </Grid.RowDefinitions>
                    <Label Grid.Column="0" Grid.Row="0" Content="轮廓距离" VerticalAlignment="Center" />
                    <TextBox Grid.Column="1" Grid.Row="0" Height="25" Text="{Binding Options.OutlineDistance, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" VerticalAlignment="Center" />
                    <Label Grid.Column="2" Grid.Row="0" Content="cm" VerticalAlignment="Center" />
                    <Label Grid.Column="0" Grid.Row="1" Content="LP之间的距离" VerticalAlignment="Center" />
                    <TextBox Grid.Column="1" Grid.Row="1" Height="25" Text="{Binding Options.DistanceBetweenLp, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" VerticalAlignment="Center" />
                    <Label Grid.Column="2" Grid.Row="1" Content="cm" VerticalAlignment="Center" />
                    <Label Grid.Column="0" Grid.Row="2" Content="LP和LD之间的距离" VerticalAlignment="Center" />
                    <TextBox Grid.Column="1" Grid.Row="2" Height="25" Text="{Binding Options.DistanceBetweenLpAndLd, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" VerticalAlignment="Center" />
                    <Label Grid.Column="2" Grid.Row="2" Content="cm" VerticalAlignment="Center" />
                </Grid>
                <Button Content="保存更改" Command="{Binding Update}" Margin="0,10,0,0" FontSize="11" />
            </StackPanel>
        </GroupBox>

        <GroupBox Header="款式" Margin="10">
            <StackPanel Margin="10">
                <CheckBox Content="仅填充" IsChecked="{Binding OnlyCimbrament, Mode=TwoWay}" />
                <Grid Margin="0,10,0,0">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="1.5*"></ColumnDefinition>
                        <ColumnDefinition Width="3*"></ColumnDefinition>
                    </Grid.ColumnDefinitions>

                    <Label Grid.Column="0" Content="方向:" Width="80" HorizontalAlignment="Left" VerticalAlignment="Center" />
                    <ComboBox Grid.Column="1" ItemsSource="{Binding Source={StaticResource OrientationsList}}" SelectedItem="{Binding SelectedOrientation, Mode=TwoWay}" VerticalAlignment="Center" />
                </Grid>
            </StackPanel>
        </GroupBox>
    </StackPanel>

    <UserControl.ContextMenu>
        <ContextMenu>
            <MenuItem Header="重置图案" Command="{Binding Reset}" />
        </ContextMenu>
    </UserControl.ContextMenu>
</UserControl>